#!/bin/bash
set -euo pipefail

# v30 Zee margined preset (0122). Source tree is NOT tmp/v30 — set YNAVI_V30_SRC or use tracked src-v30/.
repoRoot="$(cd "$(dirname "$0")" && pwd)"
v30Src="${YNAVI_V30_SRC:-$repoRoot/src-v30}"

if [[ ! -f "$v30Src/apktool.yml" ]]; then
  echo "Error: v30 apktool tree missing at: $v30Src"
  echo "Release SoT is a tracked tree (src-v30/) or YNAVI_V30_SRC — not ignored tmp/v30/."
  exit 1
fi

tmpCfg="$(mktemp -t ynavi-zee-v30-config.XXXXXX.env)"
cleanup() { rm -f "$tmpCfg" >/dev/null 2>&1 || true; }
trap cleanup EXIT

cat >"$tmpCfg" <<'EOF'
# Auto-generated by build_zeekr_v30.sh (do not commit)
ZEEAPP_LETTERBOX_TOP_DIP=70.0
ZEEAPP_LETTERBOX_BOTTOM_DIP=10.0
ZEEAPP_LETTERBOX_LEFT_DIP=480.0
ZEEAPP_UI_SCALE_PERCENT=175
ZEEAPP_MAP_SCALE_PERCENT=130
ZEEAPP_ENABLE_AD_BANNERS=0
ZEEAPP_ENABLE_PROMO_BANNERS=0
ZEEAPP_KEEPALIVE_ENABLED=1
ZEEAPP_KEEPALIVE_MODE=fgs
ZEEAPP_KEEPALIVE_RECEIVER_EXPORTED_DEBUG=0
EOF

bash "$repoRoot/build_apk.sh" \
  -inputFolder "$v30Src" \
  -outputFile "$repoRoot/builds/ynavi_v30_zeekr.apk" \
  -configFile "$tmpCfg"
