#!/bin/bash
set -euo pipefail

# Zeekr OS7+ preset — left letterbox DISABLED (panel layout differs on OS7+):
# - top=70dp, bottom=10dp, left=0dp
# - ui scale=175%, map scale=130%, keepalive=1 (same as build_zeekr.sh)

repoRoot="$(cd "$(dirname "$0")" && pwd)"

tmpCfg="$(mktemp -t ynavi-zee-config.XXXXXX.env)"
cleanup() { rm -f "$tmpCfg" >/dev/null 2>&1 || true; }
trap cleanup EXIT

cat >"$tmpCfg" <<'CFGEOF'
# Auto-generated by build_zeekr_os7.sh (do not commit)
ZEEAPP_LETTERBOX_TOP_DIP=70.0
ZEEAPP_LETTERBOX_BOTTOM_DIP=10.0
ZEEAPP_LETTERBOX_LEFT_DIP=0.0
ZEEAPP_UI_SCALE_PERCENT=175
ZEEAPP_MAP_SCALE_PERCENT=130
ZEEAPP_ENABLE_AD_BANNERS=0
ZEEAPP_ENABLE_PROMO_BANNERS=0
ZEEAPP_KEEPALIVE_ENABLED=1
ZEEAPP_KEEPALIVE_MODE=fgs
ZEEAPP_KEEPALIVE_RECEIVER_EXPORTED_DEBUG=0
CFGEOF

bash "$repoRoot/build_apk.sh" \
  -inputFolder "$repoRoot/src" \
  -outputFile "$repoRoot/builds/zeekr_os7.apk" \
  -configFile "$tmpCfg"
