#!/bin/bash
set -euo pipefail

# Deepal preset:
# - top=91dp, bottom=91dp, left=0dp
# - ui scale=175%, keepalive=1

repoRoot="$(cd "$(dirname "$0")" && pwd)"

tmpCfg="$(mktemp -t ynavi-zee-config.XXXXXX.env)"
cleanup() { rm -f "$tmpCfg" >/dev/null 2>&1 || true; }
trap cleanup EXIT

cat >"$tmpCfg" <<'EOF'
# Auto-generated by build_deepal.sh (do not commit)
ZEEAPP_LETTERBOX_TOP_DIP=91.0
ZEEAPP_LETTERBOX_BOTTOM_DIP=91.0
ZEEAPP_LETTERBOX_LEFT_DIP=0.0
ZEEAPP_UI_SCALE_PERCENT=175
ZEEAPP_MAP_SCALE_PERCENT=130
ZEEAPP_KEEPALIVE_ENABLED=1
ZEEAPP_KEEPALIVE_RECEIVER_EXPORTED_DEBUG=0
EOF

zsh "$repoRoot/build_apk.sh" \
  -inputFolder "$repoRoot/src" \
  -outputFile "$repoRoot/builds/deepal.apk" \
  -configFile "$tmpCfg"

