#!/bin/bash
set -euo pipefail

# Zeekr preset without keepalive:
# - top=70dp, bottom=10dp, left=480dp
# - ui scale=175%, map scale=130%, keepalive=0

repoRoot="$(cd "$(dirname "$0")" && pwd)"

tmpCfg="$(mktemp -t ynavi-zee-config.XXXXXX.env)"
cleanup() { rm -f "$tmpCfg" >/dev/null 2>&1 || true; }
trap cleanup EXIT

cat >"$tmpCfg" <<'EOF'
# Auto-generated by build_zeekr_no_keepalive.sh (do not commit)
ZEEAPP_LETTERBOX_TOP_DIP=70.0
ZEEAPP_LETTERBOX_BOTTOM_DIP=10.0
ZEEAPP_LETTERBOX_LEFT_DIP=480.0
ZEEAPP_UI_SCALE_PERCENT=175
ZEEAPP_MAP_SCALE_PERCENT=130
ZEEAPP_KEEPALIVE_ENABLED=0
ZEEAPP_KEEPALIVE_MODE=off
ZEEAPP_KEEPALIVE_RECEIVER_EXPORTED_DEBUG=0
EOF

zsh "$repoRoot/build_apk.sh" \
  -inputFolder "$repoRoot/src" \
  -outputFile "$repoRoot/builds/zeekr_no_keepalive.apk" \
  -configFile "$tmpCfg"