#!/bin/bash
set -euo pipefail

# Zeekr margined preset for v30 line (release/v30/src). Adjust dimens when v30 tree lands.

repoRoot="$(cd "$(dirname "$0")/../.." && pwd)"
v30Src="$repoRoot/release/v30/src"

if [[ ! -f "$v30Src/apktool.yml" ]]; then
  echo "Error: missing $v30Src/apktool.yml — see release/v30/README.md"
  exit 1
fi

tmpCfg="$(mktemp -t ynavi-v30-config.XXXXXX.env)"
cleanup() { rm -f "$tmpCfg" >/dev/null 2>&1 || true; }
trap cleanup EXIT

cat >"$tmpCfg" <<'EOF'
# Auto-generated by release/v30/build_zeekr.sh
ZEEAPP_LETTERBOX_TOP_DIP=70.0
ZEEAPP_LETTERBOX_BOTTOM_DIP=10.0
ZEEAPP_LETTERBOX_LEFT_DIP=480.0
ZEEAPP_UI_SCALE_PERCENT=175
ZEEAPP_MAP_SCALE_PERCENT=130
ZEEAPP_ENABLE_AD_BANNERS=0
ZEEAPP_ENABLE_PROMO_BANNERS=0
ZEEAPP_KEEPALIVE_ENABLED=1
ZEEAPP_KEEPALIVE_MODE=fgs
ZEEAPP_KEEPALIVE_RECEIVER_EXPORTED_DEBUG=0
EOF

bash "$repoRoot/build_apk.sh" \
  -inputFolder "$v30Src" \
  -outputFile "$repoRoot/builds/zeekr.apk" \
  -configFile "$tmpCfg"
